name: build

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at 02:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: "24"
      - run: npm run build

      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git branch -D build || true
          git checkout --orphan build
          mv build/*.rsc ${{ runner.temp }}
          git rm -rf .
          mv ${{ runner.temp }}/*.rsc .
          git add *.rsc
          git commit -m "⚡build: $(date +%Y/%m/%d)" || echo "No changes to commit"
          git push origin build --force
